### ISSUE TITLE
"moenchZmqProcess kill" doesn't work properly

### ISSUE THREAD

**Issue by lrlunin** [MBI-Div-B/pytango-moenchDetector#1]
moenchZmqProcess executable runs multiple thread with their own PIDs, which will not be terminated on subprocess.kill() call.

**Comment by dschick** [comment]
Is this an issue of the TangoDS or does it also happen in pure python?

**Comment by lrlunin** [comment]
Running the same sequence of commands in `ipython` works fine. However, it is not a big deal. The processes can be easily found by name.

**Comment by dschick** [comment]
How about python scripts vs ipython?
I do not know if python or the TangoDS behave differently about threading, etc.
