### ISSUE TITLE
Provide a preview of last aquired capture direct via zmq stream

### ISSUE THREAD

**Issue by lrlunin** [MBI-Div-B/pytango-moenchDetector#2]
Current solution relies be based on writing of a temporary file on a disk. The better one should read the data direct from RAM via zmq. Await further instructions in the github repo issue https://github.com/slsdetectorgroup/slsDetectorPackage/issues/337#issue-1077805722

**Comment by dschick** [comment]
does the `zmq` approach allow for easliy generating an average image?
I mean, in Tango we cannot handle all image files generated, there must be at least a sub-layer generating an average/sum image

**Comment by lrlunin** [comment]
Are there any bad consequences to do something like that:
```
@command
def get_last_aquired():
    data = np.array(zmq_stream)
    return np.sum(data)
```
I suppose that such a ~~krasser~~ powerfull PC with a big amount of RAM won't stuck or crash on invoke of this operation.

**Comment by dschick** [comment]
okay, we have to try that, but this would limit the TangoDS to run on the Moench host PC, which is a reasonable limition in my opinion

**Comment by lrlunin** [comment]
there is an additional information provided in a personal email as a response to my previously opened issue in github:

**Here is a short example that we can use as a basis for discussion and further development.**

https://gist.github.com/erikfrojdh/d96b8400eddbc483292de22a4c93587d


**It uses the slsdet python package and pyzmq to connect to the receiver zmq stream and read one frame.**
