### ISSUE TITLE
The tango.Device.state and slsdet.Detector.state properties sync

### ISSUE THREAD

**Issue by lrlunin** [MBI-Div-B/pytango-moenchDetector#3]
There are two identical properties in the `tango.Device` and `slsdet.Detector`. So, if a tango proxy device server is used its `state` should be correctly synchronized (polling strategy, determine state chaninging events etc).

**Comment by dschick** [comment]
this is in general a good idea, but be aware that Tango defines a certain set up states:
https://tango-controls.readthedocs.io/en/latest/development/device-api/ds-guideline/device-server-guidelines.html#device-state

maybe you can check which states are supported in the `Lima` framework

**Comment by lrlunin** [comment]
done in https://github.com/MBI-Div-B/pytango-moenchDetector/commit/7bc1a69cc0d6fe62a71f22a0b74f988a4c8722cf
